package com.alexu.bookstore.repository;

import com.alexu.bookstore.model.Author;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

@Repository
public class AuthorRepository {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    // 1. Get All Authors
    public List<Author> findAll() {
        String sql = "SELECT * FROM Author";
        return jdbcTemplate.query(sql, new AuthorRowMapper());
    }

    // 2. Add New Author
    public int save(Author author) {
        String sql = "INSERT INTO Author (name) VALUES (?)";
        // ID is usually auto-generated by the DB, so we only insert the name
        return jdbcTemplate.update(sql, author.getName());
    }

    // Mapper: DB Row -> Java Object
    private static class AuthorRowMapper implements RowMapper<Author> {
        @Override
        public Author mapRow(ResultSet rs, int rowNum) throws SQLException {
            return new Author(
                rs.getInt("id"),
                rs.getString("name")
            );
        }
    }
}